@IsTest
private class DataViewerComponentControllerTests {

	/*private static final DataViewerMock.ofIComponentPresenter mockPresenter;
    private static DataViewerComponentController sut;
    
    static {
    	mockPresenter = new DataViewerMock.ofIComponentPresenter();
        sut = new DataViewerComponentController(mockPresenter);
    }

    private static testMethod void it_should_call_the_presenter_to_initialize() {
    	String x =  'rpt-name';
    	String y = 'test';
    	boolean z = true;
	    sut.dvReportNameAttribute =  x;
		sut.contextIdAttribute = y;
		sut.debugModeAttribute = z;

    	DataViewer.ComponentViewModel result =  sut.vm;

    	mockPresenter.verify('initialize', new List<Object>{x, y,  z}, Times.Once);
    }

    private static testMethod void code_coverage() {
    	DataViewerComponentController xSut = new DataViewerComponentController();
    }*/
}