public class DmContact {
    public string id {get;set;}
    public string accountId {get;set;}
    public string firstName {get;set;}
    public string lastName {get;set;}
    public string phone {get;set;}
    public string mobilePhone {get;set;}
    public string mailingStreet {get;set;}
    public string mailingCity {get;set;}
    public string mailingState {get;set;}
    public string mailingPostalCode {get;set;}
    public string coreFirstName {get;set;}
    public string coreLastName {get;set;}
    public string syncKey {get;set;}
    public string importSource {get;set;}
}