public class DmContactReview {
    public string Id {get;set;}
    public string firstName {get;set;}
    public string lastName {get;set;}
    public string phone {get;set;}
    public string mobilePhone {get;set;}
    public string mailingStreet {get;set;}
    public string mailingCity {get;set;}
    public string mailingState {get;set;}
    public string mailingPostalCode {get;set;}
    public string key {get;set;}
    public string importSource {get;set;}
    public DmEntity entity {get;set;}
}