public class DmCPDocumentRequest {
    public String Id{get;set;}
	public Date DocumentDueDate{get;set;}
    public string DocumentName{get;set;}
    public string DocumentPortalName{get;set;}
    public string DocumentDescription{get;set;}
    public string ObjectDescription{get;set;}
    public string ObjectId{get;set;}
    public string ObjectType{get;set;}
    public string RecordId{get;set;}
    public string SourceId{get;set;}
    public string Source{get;set;}
    public string Status{get;set;}
}