public class DmTmRule {
    public String Id {get;set;}
    public String Name {get;set;}
    public String FieldName {get;set;}
    public String ObjectName {get;set;}
    public String StageId {get;set;}
    public String Product {get;set;}
    public String Error {get;set;}
    public String Operation {get;set;}
    public String Operand {get;set;}
    public String ParentId {get;set;}
    public boolean Correlated {get;set;}
    public String Formula {get;set;}
    public String FormulaToken {get;set;}
}