public class PM_CP_Document_Request_c extends PM_SObject {
    public Date DocumentDueDate_c{get;set;}
    public string DocumentName_c{get;set;}
    public string DocumentPortalName_c{get;set;}
    public string DocumentDescription_c{get;set;}
    public string ObjectDescription_c{get;set;}
    public string ObjectId_c{get;set;}
    public string ObjectType_c{get;set;}
    public string Record_Id_18_c{get;set;}
    public string SourceId_c{get;set;}
    public string Source_c{get;set;}
    public string Status_c{get;set;}
}