public class TmArchivingConfiguration implements TmArchiving.IConfiguration {
	public String GOLDMAN_SACHS(){return 'Goldman Sachs';}
    public String SWEEP_GOLDMAN_SACHS(){return 'Sweep - Goldman Sachs';}
    public String MONEY_MARKET(){return 'Money Market';}
    public String SWEEP_MONEY_MARKET(){return 'Sweep - Money Market';}
    public String OPTIMA_PLUS(){return 'Optima Plus';}
    public String SWEEP_OPTIMA_PLUS(){return 'Sweep - Optima Plus';}
    public String REPO(){return 'Repo';}
    public String SWEEP_REPO(){return 'Sweep - Repo';}
    public String CONVENTIONAL(){return 'Conventional';}
    public String PAYEE(){return 'Payee';}
    public String REVERSE(){return 'Reverse';}
    public String POSITIVE_PAY_CONVENTIONAL(){return 'Positive Pay - Conventional';}
    public String POSITIVE_PAY_REVERSE(){return 'Positive Pay - Reverse';}
    public String POSITIVE_PAY_PAYEE(){return 'Positive Pay - Payee';}
    public String REMOTE_DEPOSIT_DESKTOP(){return 'Remote Deposit - Desktop';}
    public String REMOTE_DEPOSIT_MOBILE(){return 'Remote Deposit - Mobile';}
    public String NONE(){return 'None';}
    public String QUICKBOOKS_PEACHTREE(){return 'Quickbooks/Peachtree';}
    public String DYNAMICS_NETSUITE_INTAACT(){return 'Dynamics/NetSuite/Intaact';}
    public String SAP_ERP(){return 'SAP/ERP';}

    public String ACCESS_SUPERVISOR(){ return 'Supervisor';}
    public String OLD_SUPERVISOR(){ return 'OLB_Supervisor__c';}
    public String ACCESS_LEVEL(){ return 'Access_Level__c';}
    public String OTHER(){ return 'other';}

    public String RECORDTYPE_ACH_DEBIT_FILTER(){return 'ACH Debit Filter';}
    public String RECORDTYPE_ACH_POSITIVE_PAY(){return 'ACH Positive Pay';}
    public String RECORDTYPE_ACH(){return 'ACH';}
    public String RECORDTYPE_LOCKBOX(){return 'Lockbox';}
    public String RECORDTYPE_LOCKBOX_DATA_REMITTANCE_MODULE(){return 'Lockbox - Data Remittance Module';}
    public String RECORDTYPE_LOCKBOX_REMITTANCE_IMAGING(){return 'Lockbox - Remittance Imaging';}
    public String RECORDTYPE_LOCKBOX_DATA_ENTRY_MODULE(){return 'Lockbox - Data Entry Module';}
    public String RECORDTYPE_LOCKBOX_DATA_EXTRACT_MODULE(){return 'Lockbox - Data Extract Module';}
    public String RECORDTYPE_ONLINE_BANKING(){return 'Online Banking';}
    public String RECORDTYPE_CONTROLLED_DISBURSEMENT(){return 'Controlled Disbursement';}
    public String RECORDTYPE_EDI(){return 'EDI';}
    public String RECORDTYPE_EB_ROM(){return 'EB-ROM';}
    public String RECORDTYPE_ENTERPRISE_AUTOMATED_PAYABLES(){return 'Enterprise Automated Payables';}
    public String RECORDTYPE_INVESTMENT_SWEEP(){return 'Investment Sweep';}
    public String RECORDTYPE_LOAN_INVESTMENT_SWEEP(){return 'Loan, Loan/Investment Sweep';}
    public String RECORDTYPE_POSITIVE_PAY(){return 'Positive Pay';}
    public String RECORDTYPE_REMIT_PLUS(){return 'Remit Plus';}
    public String RECORDTYPE_REMOTE_DEPOSIT(){return 'Remote Deposit';}
    public String RECORDTYPE_WIRES(){return 'Wires';}
    public String RECORDTYPE_ZBA(){return 'ZBA';}
    public String RECORDTYPE_SVC_COMMERCIAL_ONLINE_BANKING(){return 'Commercial Online Banking';}
    public String RECORDTYPE_OTHER_TM_PRODUCT(){return 'Other TM Product';}
    public String RECORDTYPE_BUSINESS_BILL_PAY(){return 'Business Bill Pay';}

    public String ONLINE_BANKING_ACH_MODULE() {return 'Online Banking - ACH Module';}
    public String SVC_PRODUCT_SAME_DAY_ACH(){return 'Same Day ACH';}
    public String SVC_PRODUCT_ACH_RETURN_TRANSMISSION(){return 'ACH Return Transmission';}
    public String SVC_PRODUCT_ACH_FTP(){return 'ACH FTP';}
    public String SVC_PRODUCT_POSITIVE_PAY_AUTOMATION(){return 'Positive Pay - Automation';}
    public String SVC_PRODUCT_POSITIVE_PAY_FILE_WIZARD(){return 'File Wizard';}
    public String SVC_PRODUCT_OTHER(){return 'Other';}
}